services:

  workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./workbench/config:/config
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

    
